### ISSUE TITLE
host and userhost need to be included in config

### ISSUE THREAD

**Issue by dseven** [rayzorben/bluecherry-docker#1]
Hello,

Thanks for sharing this! I wanted to check out BC without corrupting my existing environment or building a new host.

This didn't quite work for me, though - it failed the package install, as it was attempting to find mysql on "localhost", which is isolated within the container. After a bit of reverse-engineering, I was able to get it to basically work with the change below.

```
# git diff
diff --git a/Dockerfile b/Dockerfile
index e128be0..5f1bd47 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -69,6 +69,8 @@ RUN { \
     { \
         echo bluecherry bluecherry/mysql_admin_login password $MYSQL_ADMIN_LOGIN;       \
         echo bluecherry bluecherry/mysql_admin_password password $MYSQL_ADMIN_PASSWORD; \
+        echo bluecherry bluecherry/db_host string $host;                                \
+        echo bluecherry bluecherry/db_userhost string $userhost;                        \
         echo bluecherry bluecherry/db_name string $dbname;                              \
         echo bluecherry bluecherry/db_user string $user;                                \
         echo bluecherry bluecherry/db_password password $password;                      \
# 
```

**Comment by rayzorben** [comment]
Yes, I had meant to add that after my last change and got busy.

Fixed

https://github.com/rayzorben/bluecherry-docker/commit/65c49ce9b61e6e1441e6eb5e832ac216b57703a9
